Implemented push notification when user create summary
bobness/inspect-app pull request #30
Opened 2022-09-14 15:41 UTC by dreitec

2022-09-16 00:13 UTC, bobness requested changes
Looks like a good start, but I had a few requests

2022-09-16 00:13 UTC, bobness commented on App.tsx
> +      data: shareObject,
Why is the data passed via navigation and also via `shareUrl` `useState`? I'm guessing because now it's *only* being used from the navigation -- if so, remove `shareUrl` here unless it's used elsewhere

2022-09-16 00:13 UTC, bobness commented on src/pages/SummaryScreen.tsx
> +  shareUrl?: string;
Remove `shareUrl` and `setShareUrl` as props since it doesn't seem to be used anymore -- data is in the `data` navigation prop

2022-09-16 00:13 UTC, bobness commented on App.tsx
>  import ShareModal from "./src/components/ShareModal";
Since `SummaryScreen` is that way to do this now, I assume this file should be removed?

2022-09-16 00:13 UTC, bobness commented on src/pages/SummaryScreen.tsx
> +        // instance.get(url).then((res) => {
Make sure to copy/paste my `defaultTitle` checkbox code from `ShareModal` before deleting it (and anything else that `SummaryScreen` doesn't have)

2022-09-16 00:13 UTC, bobness commented on src/pages/SummaryScreen.tsx
> +        // instance.get(url).then((res) => {
This comment is here because getting the `url`'s contents is necessary to get `<head><title>` from the page for the 'default' Inspect title

2022-09-16 00:13 UTC, bobness commented on src/pages/SummaryScreen.tsx
> +      setSnippets([...snippets, { value: data.text }]);
What's this doing? i.e., what is `data.text`?

2022-09-16 00:13 UTC, bobness commented on src/pages/SummaryScreen.tsx
> +    // setDefaultTitle(undefined)
Ditto on `defaultTitle` logic from `ShareModal`

2022-09-16 17:35 UTC, dreitec commented on App.tsx
>        // console.log("*** setting shareUrl: ", shareObject.weblink); // DEBUG
Removed

2022-09-16 17:36 UTC, dreitec commented on App.tsx
> +      data: shareObject,
Removed

2022-09-16 17:36 UTC, dreitec commented on src/pages/SummaryScreen.tsx
> +  shareUrl?: string;
Removed

2022-09-16 17:37 UTC, dreitec commented on App.tsx
>  import ShareModal from "./src/components/ShareModal";
Yeah, I think your modal is not required, but For now, you need to keep that too, because, we need to test SummaryScreen again if it's working well as you expected.

2022-09-16 17:38 UTC, dreitec commented on src/pages/SummaryScreen.tsx
> +        // instance.get(url).then((res) => {
Copied that logic from ShareModal and implemented it on SummaryScreen

2022-09-16 17:39 UTC, dreitec commented on src/pages/SummaryScreen.tsx
> +      setSnippets([...snippets, { value: data.text }]);
When you share text from the browser, it's getting from data.text. Ideally, it's for getting snippets.

2022-09-23 00:18 UTC, bobness commented on App.tsx
>  import ShareModal from "./src/components/ShareModal";
Ah, OK. I'll put a `TODO` item to remove it after confirmation then

2022-09-27 02:01 UTC, bobness commented on src/pages/HomeScreen.tsx
> +              {/* FIXME: is in front of the above news, rather than below it */}
FIXME: The `Follow others to stay up-to-date on the news!` component occludes existing news items if there are enough

2022-09-27 02:01 UTC, bobness commented on App.tsx
> +    // FIXME: handleToken() gets called with undefined
FIXME: cited here -- https://github.com/bobness/inspect-service/pull/9#issuecomment-1258866122

2022-09-27 02:02 UTC, bobness commented on src/components/NewsRow.tsx
> +// FIXME: dragging gets stuck
FIXME: dragging animations not working

2022-09-27 02:02 UTC, bobness commented on src/pages/SummaryScreen.tsx
> +    // FIXME: selecting text in an article and sharing it does not include the weblink, so how should we do snippets?
FIXME: selecting text in an article and sharing it does not include the weblink, so how should we do snippets?

2022-09-27 02:10 UTC, bobness commented on src/store/api.js
>  // const baseUrl = "http://inspect.datagotchi.net:5000";
TODO: make sure to revert to `inspect.datagotchi.net` after done debugging

2022-10-17 05:36 UTC, dreitec commented on App.tsx
> +    // FIXME: handleToken() gets called with undefined
Please check this issue on a real device again, not a simulator.

2022-10-17 22:28 UTC, bobness commented on App.tsx
> +    // FIXME: handleToken() gets called with undefined
I need the simulator to submit a summary, but I use my iPad to read it (after hopefully getting the notification).

2022-10-18 20:57 UTC, bobness commented on App.tsx
> +    // FIXME: handleToken() gets called with undefined
Will test this after merging the PR -- and then remove the `FIXME`

2022-10-18 20:57 UTC, bobness approved these changes

2022-10-18 20:58 UTC, merged